export type AgentItem = {
  slug: string;
  image: string;
  name: string;
  role: string;
  position: string;
  specialty: string;
  practiceArea: string;
  location: string;
  experience: string;
  address: string;
  phone: string;
  email: string;
  fax: string;
  completedProjects: number;
  likes: number;
  followers: number;
  profileViews: number;
  personalExperience: string[];
};

export const agentItems: AgentItem[] = [
  {
    slug: 'henry-barton',
    image: '/theme/images/team/1.jpg',
    name: 'Henry Barton',
    role: 'Team Leader',
    position: 'Lead Response Technician',
    specialty: 'General plumbing',
    practiceArea: 'Emergency plumbing coordination',
    location: 'SEOUL',
    experience: '14 Years',
    address: 'Teheran-ro 418, Gangnam-gu, Seoul 06192',
    phone: '+82 10 2469 4411',
    email: 'henry.barton@nearhelp.kr',
    fax: '02 568 7411',
    completedProjects: 86,
    likes: 1320,
    followers: 468,
    profileViews: 44,
    personalExperience: [
      'Henry has led high-priority plumbing response work across apartment towers, mixed-use buildings, and private homes where fast diagnosis matters as much as technical repair quality. His work style is practical, calm under pressure, and focused on keeping homeowners informed before and after each major service decision.',
      'Over the years, he has specialized in burst pipe response, leak isolation, and coordination between inspection, repair, and follow-up clean-up. Clients tend to trust him for jobs that need both speed and clear communication, especially when a repair affects multiple rooms or shared building lines.',
    ],
  },
  {
    slug: 'mattie-washington',
    image: '/theme/images/team/2.jpg',
    name: 'Mattie Washington',
    role: 'Junior Member',
    position: 'Kitchen Service Specialist',
    specialty: 'Kitchen repair',
    practiceArea: 'Sink, drain, and fixture support',
    location: 'BUSAN',
    experience: '12 Years',
    address: 'Centum Jungang-ro 97, Haeundae-gu, Busan 48058',
    phone: '+82 10 5687 4698',
    email: 'mattie.washington@nearhelp.kr',
    fax: '051 746 0987',
    completedProjects: 74,
    likes: 1188,
    followers: 402,
    profileViews: 32,
    personalExperience: [
      'Mattie focuses on kitchen-side repairs where homeowners need accurate scope review before a small issue turns into cabinet damage, odor problems, or recurring drainage trouble. He is known for explaining repair causes in simple terms and helping customers understand what needs immediate action versus what can be scheduled later.',
      'His recent work has included trap replacement, fixture resets, under-sink leak correction, and cleanup-friendly repair visits for busy households. That practical experience makes him a reliable fit for homes that want clear expectations, clean workmanship, and solid follow-through after the appointment is closed.',
    ],
  },
  {
    slug: 'winifred-harmon',
    image: '/theme/images/team/3.jpg',
    name: 'Winifred Harmon',
    role: 'Team Leader',
    position: 'Gas Safety Team Lead',
    specialty: 'Gas line safety',
    practiceArea: 'Inspection and safe hookup planning',
    location: 'INCHEON',
    experience: '13 Years',
    address: 'Songdo Munhwa-ro 119, Yeonsu-gu, Incheon 21984',
    phone: '+82 10 2469 4422',
    email: 'winifred.harmon@nearhelp.kr',
    fax: '032 746 1102',
    completedProjects: 74,
    likes: 1210,
    followers: 397,
    profileViews: 29,
    personalExperience: [
      'Winifred works on gas-related service coordination where safety documentation, inspection timing, and careful communication are essential. He is often assigned when a household needs a measured approach to appliance hookup, line review, or leak-risk assessment with minimal disruption.',
      'His strength is combining field experience with disciplined safety habits, which helps homeowners feel more confident about approvals, preparation, and post-service checks. He also works closely with scheduling teams when a service requires staged visits rather than a single appointment window.',
    ],
  },
  {
    slug: 'shelia-lawrence',
    image: '/theme/images/team/4.jpg',
    name: 'Shelia Lawrence',
    role: 'Senior Member',
    position: 'Bathroom Repair Consultant',
    specialty: 'Bathroom service',
    practiceArea: 'Fixtures, drainage, and moisture checks',
    location: 'DAEGU',
    experience: '11 Years',
    address: 'Dongdaegu-ro 305, Suseong-gu, Daegu 42117',
    phone: '+82 10 2469 4433',
    email: 'shelia.lawrence@nearhelp.kr',
    fax: '053 781 3305',
    completedProjects: 61,
    likes: 980,
    followers: 355,
    profileViews: 27,
    personalExperience: [
      'Shelia handles bathroom-side work where leaking fixtures, poor drainage, seal failure, or older fittings are affecting comfort and day-to-day use. Her service record is strongest on repair plans that need careful inspection before replacement decisions are made.',
      'She is especially effective with homeowners who want realistic guidance on whether a problem needs a full remodel scope or just a focused repair visit. That balance between practical repair judgment and customer communication is what keeps her ranking consistently high.',
    ],
  },
  {
    slug: 'elijah-foster',
    image: '/theme/images/team/1.jpg',
    name: 'Elijah Foster',
    role: 'Field Supervisor',
    position: 'Water Line Diagnostics Supervisor',
    specialty: 'Water line diagnostics',
    practiceArea: 'Pressure issues and hidden line review',
    location: 'DAEJON',
    experience: '10 Years',
    address: 'Dunsan-ro 155, Seo-gu, Daejeon 35241',
    phone: '+82 10 2469 4444',
    email: 'elijah.foster@nearhelp.kr',
    fax: '042 602 4415',
    completedProjects: 58,
    likes: 940,
    followers: 338,
    profileViews: 25,
    personalExperience: [
      'Elijah is typically brought into jobs where standard fixture repair is not enough and the problem may be tied to pressure loss, routing issues, or older water line conditions. His inspections are structured, detail-heavy, and useful for customers who need confidence before approving deeper repair work.',
      'He also coordinates well with service teams that need to hand off from diagnosis to repair without losing notes or customer context. That makes him a strong choice when the issue seems larger than a quick one-visit fix.',
    ],
  },
  {
    slug: 'grace-kim',
    image: '/theme/images/team/2.jpg',
    name: 'Grace Kim',
    role: 'Premium Installer',
    position: 'Water Heater Support Specialist',
    specialty: 'Water heater support',
    practiceArea: 'Recovery issues and heater replacement planning',
    location: 'GYEONGJU',
    experience: '9 Years',
    address: 'Wonhyo-ro 88, Gyeongju-si, Gyeongbuk 38151',
    phone: '+82 10 2469 4455',
    email: 'grace.kim@nearhelp.kr',
    fax: '054 740 2218',
    completedProjects: 52,
    likes: 905,
    followers: 322,
    profileViews: 24,
    personalExperience: [
      'Grace supports water heater-related service requests where timing, comfort, and system reliability matter to the homeowner more than anything else. She is often selected for jobs that need a cleaner explanation of replacement timing, safe next steps, and what kind of downtime to expect during service.',
      'Her experience includes performance checks, recovery troubleshooting, and coordination for replacement-ready visits. Customers usually rate her highly because the service feels organized from the first message through the final recommendation.',
    ],
  },
  {
    slug: 'owen-park',
    image: '/theme/images/team/3.jpg',
    name: 'Owen Park',
    role: 'Gas Safety Specialist',
    position: 'Appliance Hookup Coordinator',
    specialty: 'Gas appliance hookup',
    practiceArea: 'Installation readiness and compliance checks',
    location: 'GWANGJU',
    experience: '8 Years',
    address: 'Sangmu-daero 721, Seo-gu, Gwangju 61949',
    phone: '+82 10 2469 4466',
    email: 'owen.park@nearhelp.kr',
    fax: '062 604 7712',
    completedProjects: 49,
    likes: 860,
    followers: 301,
    profileViews: 22,
    personalExperience: [
      'Owen works on appliance-side service bookings where proper hookup planning and safety sequencing are just as important as the physical installation. He is a strong fit for homeowners who want a smoother process when moving from purchase to safe in-home setup.',
      'His service background includes pre-install inspections, line condition review, and support for staged appointments when additional checks are needed before final connection. That methodical approach is why customers often return to him for related follow-up work.',
    ],
  },
  {
    slug: 'amelia-stone',
    image: '/theme/images/team/4.jpg',
    name: 'Amelia Stone',
    role: 'Remodel Coordinator',
    position: 'Bathroom Remodel Coordinator',
    specialty: 'Bathroom remodeling',
    practiceArea: 'Layout upgrades and fixture planning',
    location: 'JEJU',
    experience: '9 Years',
    address: 'Noyeon-ro 212, Jeju-si, Jeju 63147',
    phone: '+82 10 2469 4477',
    email: 'amelia.stone@nearhelp.kr',
    fax: '064 713 4208',
    completedProjects: 45,
    likes: 812,
    followers: 286,
    profileViews: 18,
    personalExperience: [
      'Amelia handles remodeling inquiries where homeowners need help comparing scope, sequencing, and the service tradeoffs between partial refresh work and full renovation. She has a practical style that helps customers understand what can be improved quickly and what requires more structured planning.',
      'Because she has worked across fixture changes, finishing coordination, and layout-sensitive updates, her appointments tend to be especially helpful during early planning. Many customers use her recommendations to move from an unclear idea to a realistic project scope they can schedule with confidence.',
    ],
  },
  {
    slug: 'lucas-bennett',
    image: '/theme/images/team/1.jpg',
    name: 'Lucas Bennett',
    role: 'Drainage Technician',
    position: 'Basement Drainage Technician',
    specialty: 'Basement plumbing',
    practiceArea: 'Drainage stability and lower-level pipe checks',
    location: 'JEONJU',
    experience: '7 Years',
    address: 'Baekje-daero 301, Wansan-gu, Jeonju 54986',
    phone: '+82 10 2469 4488',
    email: 'lucas.bennett@nearhelp.kr',
    fax: '063 284 1183',
    completedProjects: 39,
    likes: 760,
    followers: 254,
    profileViews: 17,
    personalExperience: [
      'Lucas focuses on lower-level plumbing problems where drainage behavior, moisture risk, and older infrastructure can make a small issue feel unpredictable. He is often requested for basement-side work that needs a more careful first inspection before the repair plan is finalized.',
      'His field notes tend to be detailed and useful for homeowners deciding how urgent the issue really is. That makes him especially dependable on jobs where the customer wants a realistic assessment without unnecessary upselling.',
    ],
  },
  {
    slug: 'chloe-rivera',
    image: '/theme/images/team/2.jpg',
    name: 'Chloe Rivera',
    role: 'Clean Finish Expert',
    position: 'Post-Service Clean Finish Specialist',
    specialty: 'Cleaning and post-renovation',
    practiceArea: 'Reset cleaning and move-in readiness',
    location: 'SEOUL',
    experience: '8 Years',
    address: 'Mapo-daero 58, Mapo-gu, Seoul 04168',
    phone: '+82 10 2469 4499',
    email: 'chloe.rivera@nearhelp.kr',
    fax: '02 335 6621',
    completedProjects: 34,
    likes: 708,
    followers: 233,
    profileViews: 15,
    personalExperience: [
      'Chloe supports the finishing side of home service work, especially after repair visits, remodeling activity, or move-in prep where the final result needs to feel clean and ready rather than simply completed. She is valued for being organized, responsive, and detail-aware during the last stage of a service journey.',
      'Her experience makes her a strong partner when the homeowner cares about presentation, handoff quality, and making the space usable again without extra follow-up. That attention to final condition is what drives her strong feedback from repeat customers.',
    ],
  },
];

export const getAgentBySlug = (slug: string) => agentItems.find((item) => item.slug === slug);
