export type AgentItem = {
  slug: string;
  image: string;
  name: string;
  role: string;
  specialty: string;
  location: string;
  completedProjects: number;
  likes: number;
  followers: number;
  profileViews: number;
};

export const agentItems: AgentItem[] = [
  {
    slug: 'henry-barton',
    image: '/theme/images/team/1.jpg',
    name: 'Henry Barton',
    role: 'Team Leader',
    specialty: 'General plumbing',
    location: 'SEOUL',
    completedProjects: 86,
    likes: 1320,
    followers: 468,
    profileViews: 44,
  },
  {
    slug: 'mattie-washington',
    image: '/theme/images/team/2.jpg',
    name: 'Mattie Washington',
    role: 'Junior Member',
    specialty: 'Kitchen repair',
    location: 'BUSAN',
    completedProjects: 74,
    likes: 1188,
    followers: 402,
    profileViews: 32,
  },
  {
    slug: 'winifred-harmon',
    image: '/theme/images/team/3.jpg',
    name: 'Winifred Harmon',
    role: 'Team Leader',
    specialty: 'Gas line safety',
    location: 'INCHEON',
    completedProjects: 74,
    likes: 1210,
    followers: 397,
    profileViews: 29,
  },
  {
    slug: 'shelia-lawrence',
    image: '/theme/images/team/4.jpg',
    name: 'Shelia Lawrence',
    role: 'Senior Member',
    specialty: 'Bathroom service',
    location: 'DAEGU',
    completedProjects: 61,
    likes: 980,
    followers: 355,
    profileViews: 27,
  },
  {
    slug: 'elijah-foster',
    image: '/theme/images/team/1.jpg',
    name: 'Elijah Foster',
    role: 'Field Supervisor',
    specialty: 'Water line diagnostics',
    location: 'DAEJON',
    completedProjects: 58,
    likes: 940,
    followers: 338,
    profileViews: 25,
  },
  {
    slug: 'grace-kim',
    image: '/theme/images/team/2.jpg',
    name: 'Grace Kim',
    role: 'Premium Installer',
    specialty: 'Water heater support',
    location: 'GYEONGJU',
    completedProjects: 52,
    likes: 905,
    followers: 322,
    profileViews: 24,
  },
  {
    slug: 'owen-park',
    image: '/theme/images/team/3.jpg',
    name: 'Owen Park',
    role: 'Gas Safety Specialist',
    specialty: 'Gas appliance hookup',
    location: 'GWANGJU',
    completedProjects: 49,
    likes: 860,
    followers: 301,
    profileViews: 22,
  },
  {
    slug: 'amelia-stone',
    image: '/theme/images/team/4.jpg',
    name: 'Amelia Stone',
    role: 'Remodel Coordinator',
    specialty: 'Bathroom remodeling',
    location: 'JEJU',
    completedProjects: 45,
    likes: 812,
    followers: 286,
    profileViews: 18,
  },
  {
    slug: 'lucas-bennett',
    image: '/theme/images/team/1.jpg',
    name: 'Lucas Bennett',
    role: 'Drainage Technician',
    specialty: 'Basement plumbing',
    location: 'JEONJU',
    completedProjects: 39,
    likes: 760,
    followers: 254,
    profileViews: 17,
  },
  {
    slug: 'chloe-rivera',
    image: '/theme/images/team/2.jpg',
    name: 'Chloe Rivera',
    role: 'Clean Finish Expert',
    specialty: 'Cleaning and post-renovation',
    location: 'SEOUL',
    completedProjects: 34,
    likes: 708,
    followers: 233,
    profileViews: 15,
  },
];
